### ISSUE TITLE
Firebug: TypeError: $ is not a function

### ISSUE THREAD

**Issue by razzda** [gsuez/master-bootstrap-3#10]
Firebug throws an error "TypeError: $ is not a function" for this (also happens in your own webpage):

```
<script type="text/javascript">
$('.dropdown input').click(function(e) {
e.stopPropagation();
});
</script>
```

and 

```
<script type="text/javascript">
$('.dropdown-menu .dropdown-submenu a[data-toggle="dropdown-submenu"]').click(function (e)
{                   
    e.stopPropagation();
});
</script>
```

**Comment by gsuez** [comment]
Hi razzda, test this code for the first:
<pre>
<code>
jQuery(function($){
    $('.dropdown-menu input, .dropdown-menu label').click(function(e) {
        e.stopPropagation();
    });
	});
</code>
</pre>
For the second second code, comment it, and test it :)

Let me know for news.
Regards

**Comment by gsuez** [comment]
we haven't received the required feedback
