### ISSUE TITLE
Edit layout not work

### ISSUE THREAD

**Issue by farzad123** [gsuez/master-bootstrap-3#11]
login in frontend , and edit an article , yes u can't :P 
so many bug's in this section ...

plaz fix them bro. ;)

**Comment by gsuez** [comment]
Hi!
you use the last version? I add a new code for load jquery and bootstrap from admin...
Regards

**Comment by farzad123** [comment]
yes, i use latest version (Stable 1.1-21 , DIC 2014 ) ... 
but i can't edit anything ...

edit button doesn't work and edit area isn't work fine...

**Comment by gsuez** [comment]
is jquery issue... I will fixed this week, I hope ;)
Thanks!

**Comment by gsuez** [comment]
test comment this lines in params.php
	unset($doc->_scripts[JURI::root(true) . '/media/system/js/mootools-more.js']);
	unset($doc->_scripts[JURI::root(true) . '/media/system/js/mootools-core.js']);

**Comment by webchik** [comment]
Great work on this template.  I'm also having problems editing from frontend - the Save/Cancel buttons do not work when using this template - also, the Publishing tab on front end where the datepickers are (Start Publishing/Finish Publishing) aren't working either.  Layout is a little all over the shop.

**Comment by farzad123** [comment]
@gsuez nothing changed ... 
i have all problems that @webchik said...

**Comment by gsuez** [comment]
Hi! please check the new version, update yesterday.
Please, let me know any news.

**Comment by gsuez** [comment]
we haven't received the required feedback
