### ISSUE TITLE
Main menu not working

### ISSUE THREAD

**Issue by TorstenE** [gsuez/master-bootstrap-3#12]
Hey,

I have assigned position "navigation" to the "main menu". The module classes "navbar navbar-nav-right" are not accepted. I have downloaded the latest version yesterday. Do you have an idea what I can do?

Regards

Torsten

**Comment by gsuez** [comment]
Hi!
the correct class are:

<pre>nav navbar-nav navbar-right</pre>

Write in advance tab - Menu Class Suffix

Regards

**Comment by N6REJ** [comment]
navbar-nav-right is not a valid class... go look @ bootstrap class 
documentation
Bear

**Comment by mitsol** [comment]
i think it must be: " nav navbar-nav navbar-right" -  don't forget the space as first character

**Comment by gsuez** [comment]
we haven't received the required feedback
