### ISSUE TITLE
menu hover

### ISSUE THREAD

**Issue by mitsol** [gsuez/master-bootstrap-3#14]
The menu is behaving a little bit wrong: usually you have displayed the dropdown when hovering over the items (not as it is now by clicking) and there should be the possibility to click the parent item of a dropdown, which is not possible yet.

Any suggestions how to correct this? Thanks

**Comment by gsuez** [comment]
Hi, the behavior of the menu is correct. This is the way in Bootstrap.
If you want dropdown when hovering over, add this in you css file:

`ul.nav li.dropdown:hover > ul.dropdown-menu {
    display: block;
}`

Work in last version, 1.2.1

**Comment by mitsol** [comment]
Thanks a lot, opening the submenu while hovering works now.

Still an open issue is, that i can't open the parent menu item if there is a submenu:

e.g. following structure
+ Main item 1
+ Main item 2
  -- + Subitem 1
  -- + Subitem 2
+ Main item 3

it's possible to click and access Main item 1, Main item 3 and all the subitems, but it isn't possible to access Main item 2 directly.

**Comment by gsuez** [comment]
Hi mitsol, check you site, could affect other functions if you have others dropdown.

**Comment by gsuez** [comment]
we haven't received the required feedback
