### ISSUE TITLE
Missing </div>, misordered </div>

### ISSUE THREAD

**Issue by techgump** [gsuez/master-bootstrap-3#16]
There is an issue with the html framework regarding the order of closing elements.
In the head, it's missing a closing </ div >.
And another closing </ div > for opening < div id="wrap" > closes inside of the < section >, despite the wrap div opening before < section >.
Errors can be viewed with an html validator.

**Comment by gsuez** [comment]
Hi!
from validator.w3.org, that issue is not listed.

**Comment by techgump** [comment]
Well, the validator may not explicitly be stating so, and I don't remember exactly what the errors stated, but from my findings they were due to closing tag issues. I removed all modules and content when testing, leaving just the template to render.
The easiest one to verify just by looking at index.php of template, is the < div id="wrap" > which you will see opens just after the < body > tag, well before the < section > tag opens. But the closing tag occurs before the < /section > closing, hence there is no < /div> tag after the < /section>.
Should be
< body>
  < div id="wrap" >
    < header>...
    < /header>
    < section >...
    < /section>
  < /div >
< /body >

but instead is:
< body>
  < div id="wrap" >
    < header>...
    < /header>
    < section >...
  < /div >
    < /section>
< /body >
