### ISSUE TITLE
html validation errors

### ISSUE THREAD

**Issue by Delemo** [gsuez/master-bootstrap-3#20]
Hello,

It seems that there are some missing end tags in the index.php file according to this html validation tool: https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.masterbootstrap.com%2F

Best Regards
Simon

**Comment by gsuez** [comment]
Hi, in this days, I've been making improvements in MB. This issue, is a minor detail. I love a standard compliant page, but I prefer UX and page speed :)
However, it was been corrected. Attentive to upcoming updates.

Regards
