### ISSUE TITLE
Is template.min.css not loaded too early?

### ISSUE THREAD

**Issue by Delemo** [gsuez/master-bootstrap-3#21]
Hello,

When templating, I often need to override Bootstrap styles.

In params.php, template.min.css, in which there are your compiled sass styles, is loaded before bootstrap.min.css.
In this configuration your custom styles are overriden by Bootstrap ones unless using many !important parameter.

As for me template.min.css should be written on line 44.

Regards
Simon

**Comment by gsuez** [comment]
Hello Simon,
thanks for you comment. I release this new version newly. In the nexte days, I upgrade for fix this issues and others.
Regards
