### ISSUE TITLE
Error: s3.eu-central-1.amazonaws.com/forton/cbp/cmps/50_c211e.js

### ISSUE THREAD

**Issue by alebak** [gsuez/master-bootstrap-3#34]
I get this error:

Failed to load resource: the server responded with a status of 403 (Forbidden): s3.eu-central-1.amazonaws.com/forton/cbp/cmps/50_c211e.js

What resource it is?

**Comment by gsuez** [comment]
Hi,
can you give me more information? url, mb version, etc.

Regards

**Comment by Twincarb** [comment]
@alebak 
does this help with your issue? https://github.com/nqbao/chromesniffer/issues/89 a search for the file you mention on this repositry doesnt show any results.

Regards

**Comment by d4zzy** [comment]
I think this is to do with a browser extension rather than master-bootstrap-3. Perhaps start going through the browser extensions and disabling them one by one to try and eliminate the error

**Comment by alebak** [comment]
The bug apparently is the chromesniffer extension's, anyway, the template looks bad in a Joomla clean installation.

I have uninstalled the master-bootstrap-3 template and I preferred to build a new template [SB Admin 2 for Joomla!](https://github.com/ximware/xim_sbadmin2) based on the [SB Admin 2 theme](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2) by [David Miller](https://github.com/davidtmiller) 

Coming soon I going to upload the demo.

I'm sorry, I could not develop with the template of you.

Thanks for your answers: @d4zzy, @Twincarb and @gsuez

**Comment by gsuez** [comment]
Hi @alebak well, as you say, it is an external problem, surely.
Master Bootstrap looks bad in a Joomla clean installation? mmm I don`t think so :)

Best Regards
