### ISSUE TITLE
Joomla 3.5 Supported? 

### ISSUE THREAD

**Issue by openhardwarecoza** [gsuez/master-bootstrap-3#38]
Is Joomla 3.5 Supported?  I tried uploading the release zip,  but Joomla fails to install it
Or am I missing additional steps prior to upload?

**Comment by gsuez** [comment]
Absolutely supported. Install like 
What error you get?

**Comment by openhardwarecoza** [comment]
I'll test again tonight and screencap the error if it reoccurs (:

**Comment by gsuez** [comment]
Just I`m installed in a new Joomla 3.6.5 site, all is ok. Send me you screenshot, if you get the same error.

**Comment by openhardwarecoza** [comment]
Couldnt replicate again, so consider it me who had something wrong
