### ISSUE TITLE
Can I use font awesome icons in menu / module titles? 

### ISSUE THREAD

**Issue by openhardwarecoza** [gsuez/master-bootstrap-3#39]
For example like https://www.joomlart.com/documentation/purity-iii/faqs#megamenu-icon

(: If not presently possible can we ask for it as an enhancement request?

**Comment by tonypartridge** [comment]
Yes you can, in the template config enable Font-Awesome.

**Comment by gsuez** [comment]
@openhardwarecoza read http://www.masterbootstrap.com/documentation last line :)
