### ISSUE TITLE
SASS attribute selectors don't work 

### ISSUE THREAD

**Issue by masilver99** [gsuez/master-bootstrap-3#43]
For example: 
div[itemprop="blogPost"] {
  border: 1px solid #e3e3e3;
  border-radius: 3px 3px 0 0;
}
will be removed from the compiled CSS.

The leafo version of the sass compiler is out of date.  Updating the leafo source to the latest appears to be working for me.

**Comment by gsuez** [comment]
Hi masilver99 thank you. I will check this issue.

**Comment by phproberto** [comment]
👍  
Please check: https://github.com/gsuez/master-bootstrap-3/pull/44
