### ISSUE TITLE
totally fails front end file editing.

### ISSUE THREAD

**Issue by N6REJ** [gsuez/master-bootstrap-3#7]
if you go to a article in the front end and hit "edit' the first thing you notice is a long load time ( with jce ) but the biggest thing is when you go to click on "images and links" it completely crashes with a very weird url http://localhost/ae/news/latest-pwi-news?view=form&layout=edit&a_id=908&return=aHR0cDovL2xvY2FsaG9zdC9hZS9uZXdzL2xhdGVzdC1wd2ktbmV3cw==
you can't click on the edit button from the front end either as it loses focus on hover.
These are all due to mootools conflicts

**Comment by gsuez** [comment]
Hi!
please, check the new version, regards

**Comment by N6REJ** [comment]
@gsuez did you create a new zip or do I need to pull from git?

**Comment by gsuez** [comment]
I create a new zip, please download and enjoy ;)

**Comment by N6REJ** [comment]
ty

**Comment by N6REJ** [comment]
ok, it doesn't crash now but still isn't working properly.. this is a common issue with all BS3 templates I've found..
![capture](https://cloud.githubusercontent.com/assets/1850089/6646374/34b330f0-c992-11e4-9491-8ad2f99e1009.JPG)

**Comment by N6REJ** [comment]
also, for whatever reason MENU is below content

**Comment by gsuez** [comment]
this issue, is only in images and link tabs?

**Comment by N6REJ** [comment]
from what I can see now yes.

**Comment by gsuez** [comment]
fix this issue... the menu is above the content, always... look masterbootstrap.com, is the same zip.

**Comment by gsuez** [comment]
Solved
