### ISSUE TITLE
login fail error message not showing

### ISSUE THREAD

**Issue by mryukta** [gsuez/master-bootstrap-3#8]
Hello Gsuez,

I have used this template long back for my portal (http://gampa.in/component/users/?view=login)
You can check here login showing the error message, but now in new template (http://www.masterbootstrap.com/index.php/dropdown-menu-2/login) not showing the error message.

**Comment by mryukta** [comment]
got the solution..
in index.php file above component tag <jdoc:include type="component" />
this message tag is missing... <jdoc:include type="message" />

**Comment by gsuez** [comment]
Hi mryukta!
I´m working in the next version, serveral bug will be fixed.
Thanks for you comment!
