### ISSUE TITLE
params.php

### ISSUE THREAD

**Issue by razzda** [gsuez/master-bootstrap-3#9]
In line 23 of params.php, why do you:

```
$doc->addScript('templates/'.$this->template.'/js/dropdown.js');
```

when all the dropdown code already is available in bootstrap js library?

**Comment by razzda** [comment]
Additionally:

```
$app = JFactory::getApplication();
$doc = JFactory::getDocument();
```

is called twice?

**Comment by wallstudios** [comment]
In params.php there are some references to files that are not included in the package.
$doc->addStyleSheet('templates/'.$this->template.'/css/icons.css');
if ($loadJquery==1) $doc->addScript($tpath.'/js/jquery-2.1.1.min.js');
if ($loadJquery==1) $doc->addScript($tpath.'/js/jquery-noconflict.js');
if ($loadJquery==1) $doc->addScript($tpath.'/js/jquery-migrate.min.js');

**Comment by gsuez** [comment]
Hi pals, take a look a the new version for Master Bootstrap.
Let me know any news.
Regards

**Comment by gsuez** [comment]
we haven't received the required feedback
